version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5433:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=thor2024
      - POSTGRES_USER=rolo
      - POSTGRES_DB=my_db
